// <auto-generated />
namespace najjar.biz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class test_question_limit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_question_limit));
        
        string IMigrationMetadata.Id
        {
            get { return "201908031900066_test_question_limit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
