// <auto-generated />
namespace najjar.biz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class basemodel1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basemodel1));
        
        string IMigrationMetadata.Id
        {
            get { return "201908180737164_basemodel1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
