// <auto-generated />
namespace najjar.biz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class employeeuserone2one : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeeuserone2one));
        
        string IMigrationMetadata.Id
        {
            get { return "201906281122069_employee-user-one2one"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
